//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Backend", ConfigurationName="EBInterface")]
public interface EBInterface
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Backend/EBInterface/StartBackup", ReplyAction="http://Backend/EBInterface/StartBackupResponse")]
    void StartBackup(string[] directories);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Backend/EBInterface/StartRecovery", ReplyAction="http://Backend/EBInterface/StartRecoveryResponse")]
    void StartRecovery(long fileID, System.Guid sourceNode, string outputPath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Backend/EBInterface/CheckRecovery", ReplyAction="http://Backend/EBInterface/CheckRecoveryResponse")]
    string CheckRecovery();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface EBInterfaceChannel : EBInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EBInterfaceClient : System.ServiceModel.ClientBase<EBInterface>, EBInterface
{
    
    public EBInterfaceClient()
    {
    }
    
    public EBInterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EBInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EBInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EBInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void StartBackup(string[] directories)
    {
        base.Channel.StartBackup(directories);
    }
    
    public void StartRecovery(long fileID, System.Guid sourceNode, string outputPath)
    {
        base.Channel.StartRecovery(fileID, sourceNode, outputPath);
    }
    
    public string CheckRecovery()
    {
        return base.Channel.CheckRecovery();
    }
}
